name: ptetra
channels:
  - default
  - conda-forge
dependencies:
  - python
  - pip
  - numpy
  - openmpi-mpifort
  - libgfortran
  - gmsh
  - openssl 
  - gnupg
  - pip:
    - matplotlib
    - pandas
    - langmuir
